services:
  app:
    container_name: hackathon-backend
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: ["fastapi", "dev", "app/main.py", "--host", "0.0.0.0", "--port", "8001", "--reload"]
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    restart: unless-stopped
    networks:
      - app-network
